src/Web/Shop.Web/Controllers/CreateController.cs
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Models;
using Shop.Services.Data;
using Shop.Web.CloudinaryHelper;
using Shop.Web.ViewModels.Create;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Web.Controllers
{
    public class CreateController : BaseController
    {
        private readonly IProductCreateService product;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly Cloudinary cloudinary;

        public CreateController(IProductCreateService product,
                                UserManager<ApplicationUser> userManager,
                                Cloudinary cloudinary)
        {
            this.product = product;
            this.userManager = userManager;
            this.cloudinary = cloudinary;
        }

        public IActionResult ProductCreate(int id)
        {
            this.ViewBag.BrandId = id;
            return this.View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreateAsync(ProductInputModel productInputModel, IFormFile image, ICollection<IFormFile> images, int brandId)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var createProduct =
                await this.product.CreateAsync(
                    productInputModel.Name,
                    productInputModel.Description,
                    productInputModel.Price,
                    productInputModel.Location,
                    user.Id,
                    image,
                    brandId,
                    productInputModel.Category
                    );
            if (images != null)
            {
            var img = await this.product.CreateImage(images, createProduct);
           // await CloudinaryExtension.UploadAsync(this.cloudinary, images);
            }

            return this.RedirectToAction("MyProducts", "Product");
        }

        public IActionResult Product(int id)
        {
            var productViewModel = this.product.GetById<ProductInputModel>(id);
            return this.View(productViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Upload(ICollection<IFormFile> files)
        {
            await CloudinaryExtension.UploadAsync(this.cloudinary, files);

            return Redirect("/");
        }

        public IActionResult CreateForm()
        {
            return this.View();
        }
    }
}

src/Web/Shop.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Models;
using Shop.Services.Data;
using Shop.Web.ViewModels.Create;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Web.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IProductCreateService product;
        private readonly UserManager<ApplicationUser> userManager;

        public ProductController(IProductCreateService product,
                                 UserManager<ApplicationUser> userManager)
        {
            this.product = product;
            this.userManager = userManager;
        }

        public async Task<IActionResult> ProductByName(string name)
        {
            var product = this.product.GetByName<ProductInputModel>(name);
            var count = await this.product.Count(name);
            return this.View(product);
        }

        public IActionResult Product(int id)
        {
            var productViewModel = this.product.GetById<ProductInputModel>(id);
            return this.View(productViewModel);
        }

        public IActionResult MyProducts()
        {
            var user = this.userManager.GetUserAsync(this.User).GetAwaiter().GetResult();
            var productsViewModel = new ProductsInputModel();
            productsViewModel.Products = this.product.GetUserProducts<ProductInputModel>(user.Id);

            return this.View(productsViewModel);
        }
    }
}

src/Web/Shop.Web/Views/Create/CreateForm.cshtml
<style>
    .dropdown-toggle {
        width: 100% !important;
    }
    ul li{
        width:100%;
    }
    .dropdown-menu {
        width:100%;
    }
</style>
<div class="row">
    <div class="col-6">
        <button type="button" class="btn btn-primary" onclick="createProductForm()">Добавете продукт</button>
    </div>
    <div class="col-6">
        <button type="button" class="btn btn-primary" onclick="createBrandForm()">Добавете бранд</button>
    </div>
</div>
<br />
<div id="create-product-form"  style="display:none">
    <div class="row text-center">
        <br />
        <div class="col-4">
            <form method="post" enctype="multipart/form-data" asp-controller="Create" asp-action="Create">
                <div class="form-outline mb-4">
                    <input type="text" id="form6Example3" class="form-control" name="Name" />
                    <label class="form-label" for="form6Example3">Име на продукта</label>
                </div> 
                <div class="form-outline mb-4">
                    <input type="number" id="form6Example4" class="form-control" name="Price" />
                    <label class="form-label" for="form6Example4">Цена</label>
                </div>
                <br />
                <div class="dropdown text-left">
                    <button class="btn btn-primary dropdown-toggle"
                            type="button"
                            id="dropDownCategory"
                            data-mdb-toggle="dropdown"
                            aria-expanded="false">
                        Изберете категория
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropDownCategory">
                        <li><a class="dropdown-item" href="#" onclick="changeCategoryText('Електроника')">Електроника</a></li>
                        <li><a class="dropdown-item" href="#" onclick="changeCategoryText('Мода')">Мода</a></li>
                        <li><a class="dropdown-item" href="#" onclick="changeCategoryText('За градината')">За градината</a></li>
                        <li><a class="dropdown-item" href="#" onclick="changeCategoryText('Имоти')">Имоти</a></li>
                        <li><a class="dropdown-item" href="#" onclick="changeCategoryText('Авто')">Авто</a></li>
                        <li><a class="dropdown-item" href="#" onclick="changeCategoryText('Други')">Други</a></li>
                    </ul>
                    <input id="categoryInput" type="hidden" name="category"/>
                </div>
                <br />
                <!-- Message input -->
                <div class="form-outline mb-4">
                    <textarea class="form-control" id="form6Example7" rows="4" name="Description"></textarea>
                    <label class="form-label" for="form6Example7">Описание</label>
                </div>
                <label class="form-label font-weight-bolder" for="customFile">Главна снимка</label>
                <input type="file" class="form-control" id="customFile" name="image" />

                <label class="form-label font-weight-bolder" for="customFile">Снимки</label>
                <input type="file" class="form-control" id="customFile" name="images" multiple />
                <br />
                <button type="submit" class="btn btn-primary btn-block mb-4 ">Публикувай</button>
            </form>
        </div>
    </div>
</div> 
<div id="create-brand-form" style="display:none">
    <div class="row text-center">
        <br />
        <div class="col-4">
            <form method="post" enctype="multipart/form-data" asp-controller="Brand" asp-action="Create">
                <!-- 2 column grid layout with text inputs for the first and last names -->
                <!-- Text input -->
                <div class="form-outline mb-4">
                    <input type="text" id="form6Example3" class="form-control" name="Name" />
                    <label class="form-label" for="form6Example3">Име на бранда</label>
                </div>
                <!-- Message input -->
                <div class="form-outline mb-4">
                    <textarea class="form-control" id="form6Example7" rows="4" name="Description"></textarea>
                    <label class="form-label" for="form6Example7">Описание</label>
                </div>
                <label class="form-label font-weight-bolder" for="customFile">Лого</label>
                <input type="file" class="form-control" id="customFile" name="Logo" />
                <br />
                <button type="submit" class="btn btn-primary btn-block mb-4 ">Добави</button>
            </form>
        </div>
    </div>

</div>

<script>
    function createProductForm() {
        const brandForm = document.getElementById('create-brand-form');
        const productForm = document.getElementById('create-product-form');
        brandForm.style.display = "none";
        if (productForm.style.display === "none") {
            productForm.style.display = "block"
        }

    }
    function createBrandForm() {
        const brandForm = document.getElementById('create-brand-form');
        const productForm = document.getElementById('create-product-form');
        productForm.style.display = "none";
        if (brandForm.style.display === "none") {
            brandForm.style.display = "block"
        }
    }
    function changeCategoryText(text) {
        dropDownCategory.innerHTML = text;
        categoryInput.value = text;
    }
    function changeRegionText(text) {
        dropDownRegion.innerHTML = text;
    }
</script>

src/Web/Shop.Web/Views/Create/Product.cshtml
@model Shop.Web.ViewModels.Create.ProductInputModel

    <div class="successfullyAddProductMessage">
        <h1>You have successfully added a product</h1>
    </div>
    <p>@Model.Id</p>
    <p>Product name: @Model.Name</p>
    <p>Product description @Model.Description</p>

    @foreach (var item in Model.Images)
    {
        <img src="http://res.cloudinary.com/ds1ne4hps/image/upload/@item.Name" />
        <hr />
    }

src/Web/Shop.Web/Views/Create/ProductCreate.cshtml
<form method="post" enctype="multipart/form-data" asp-controller="Create" asp-action="Create">
    <div class="form-group">
        <label for="exampleFormControlInput1">Product Name</label>
        <input type="text" name="Name" class="form-control" placeholder="Product name">
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Price</label>
        <input type="number" name="Price" class="form-control" placeholder="Price">
    </div>
    <div class="form-group">
        <label for="exampleFormControlSelect1">Region</label>
        <select class="form-control" id="exampleFormControlSelect1" name="Location">
            <option>София</option>
            <option>Пловдив</option>
            <option>Варна</option>
            <option>Бургас</option>
            <option>Русе</option>
        </select>
    </div>
    <div class="form-group">
        <label for="exampleFormControlSelect1">Category</label>
        <select class="form-control" id="exampleFormControlSelect2" name="Category">
            <option>Авто</option>
            <option>Мода</option>
            <option>Електроника</option>
            <option>Имоти</option>
            <option>Мода</option>
            <option>Други</option>
        </select>
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Description</label>
        <textarea class="form-control" name="Description" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
    <div class="form-group">
        <label for="exampleFormControlFile1">Cover Image</label>
        <input type="file" name="image" />
    </div>
    <div class="form-group">
        <label for="exampleFormControlFile1">Image</label>
        <input type="file" name="images" multiple />
    </div>
    <input type="hidden" name="brandId" value="@ViewBag.BrandId" />
    <button type="submit" class="btn btn-success btn-lg">Create</button>
</form>
 